# Generated by Django 2.1.5 on 2019-02-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player_Stats',
            new_name='Player_Stat',
        ),
    ]
