# Generated by Django 2.1.5 on 2019-02-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190222_1900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player_Stat',
            new_name='PlayerStat',
        ),
    ]
