# Generated by Django 2.1.5 on 2019-02-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerStat',
        ),
    ]
