# Generated by Django 2.1.5 on 2019-02-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_playerstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
