# Generated by Django 2.1.5 on 2019-02-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
