# Generated by Django 2.1.5 on 2019-02-28 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0002_game_gold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='won',
        ),
    ]
