# Generated by Django 2.1.5 on 2019-02-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0003_remove_game_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='won',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
