# Generated by Django 2.1.5 on 2019-03-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0009_auto_20190305_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='avacado_delay',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
