# Generated by Django 2.1.5 on 2019-03-05 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0010_mode_avacado_delay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mode',
            old_name='avacado_delay',
            new_name='avocado_delay',
        ),
    ]
