# Generated by Django 2.1.5 on 2019-03-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0011_auto_20190305_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='speed',
            field=models.IntegerField(default=4.3),
            preserve_default=False,
        ),
    ]
