# Generated by Django 2.1.5 on 2019-03-08 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boat', '0012_mode_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duskball_is', models.BooleanField(default=False)),
                ('haunted_painting_is', models.BooleanField(default=False)),
                ('lucario_is', models.BooleanField(default=False)),
                ('computer_on', models.BooleanField(default=False)),
                ('stair_collision', models.IntegerField()),
                ('cabnet_collision', models.IntegerField()),
                ('rail2_collision', models.IntegerField()),
                ('duskball_collision', models.IntegerField()),
                ('painting_collision', models.IntegerField()),
                ('haunted_collision', models.IntegerField()),
                ('lucario_collision', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='title',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
