# Generated by Django 2.1.5 on 2019-03-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0013_auto_20190308_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='computer_on',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='state',
            name='duskball_is',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='state',
            name='haunted_painting_is',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='state',
            name='lucario_is',
            field=models.BooleanField(),
        ),
    ]
