# Generated by Django 2.1.5 on 2019-03-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0015_state_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='bear_is',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='bookshelf_is',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='left_corner_is',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='move_ball_down',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='poke_ball_is',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='right_corner_is',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
