# Generated by Django 2.1.5 on 2019-03-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0016_auto_20190311_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='ball_gone',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
