# Generated by Django 2.1.5 on 2019-03-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0017_state_ball_gone'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='scroll_is',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
